<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
	<Configurations>Debug;Release</Configurations>
	<Platforms>x64</Platforms>
	<Description>Shared lib for AdiQuickLaunchItem and the AdiQuickLaunchManager</Description>
	<PackageProjectUrl>https://github.com/lukas-adrian/AdiQuickLaunch</PackageProjectUrl>
	<RepositoryUrl>https://github.com/lukas-adrian/AdiQuickLaunch</RepositoryUrl>
	<LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\icon.ico" />
    <Resource Include="Assets\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <None Remove="Assets\DefaultFolder.png" />
    <Resource Include="Assets\DefaultFolder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <None Remove="Assets\DefaultFile.png" />
    <Resource Include="Assets\DefaultFile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
