<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <PackageIcon>link.png</PackageIcon>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <Title>AdiQuickLaunchManager</Title>
    <Description>Manager to create or edit profiles for links</Description>
    <PackageProjectUrl>https://github.com/lukas-adrian/AdiQuickLaunch</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lukas-adrian/AdiQuickLaunch</RepositoryUrl>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Update="link.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\icon.ico" />
    <ProjectReference Include="..\AdiQuickLaunchLib\AdiQuickLaunchLib.csproj" />
    <Resource Include="Assets\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
